apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-downloader
  template:
    metadata:
      labels:
        app: youtube-downloader
    spec:
      containers:
      - name: server
        image: gabbersepp/youtube-download-server
        volumeMounts:
          - mountPath: /data
            name: data
            subPath: "Shared Music/Youtube"
        ports:
        - containerPort: 8081
      - name: client
        image: gabbersepp/youtube-download-client
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config
            name: clientconfig
            subPath: youtube-downloader/client
      volumes:
        - name: data
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            # secret only dummy - share is Public
            secretRef:
              name: "cifs-secret-private-cloud"
            options:
              networkPath: "//biehlercloud/Public"
              mountOptions: ""
        - name: clientconfig
          flexVolume:
            driver: "fstab/cifs"
            fsType: "cifs"
            secretRef:
              name: "cifs-secret"
            options:
              networkPath: "//192.168.2.126/sambashare"
              mountOptions: ""

---

apiVersion: v1
kind: Service
metadata:
  name: youtube-downloader
spec:
  type: ClusterIP
  selector:
    app: youtube-downloader
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: api
    port: 8081
    targetPort: 8081

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: youtube-downloader
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.2.0/8
spec:
  rules:
  - host: yt.h5b.de
    http:
      paths:
      - path: /
        backend:
          serviceName: youtube-downloader
          servicePort: 80
      - path: /api
        backend:
          serviceName: youtube-downloader
          servicePort: 8081